-- Heribhee Academy Supabase/PostgreSQL schema
-- Designed to preserve the current Telegram bot features while moving data off SQLite.

create table if not exists students (
    user_id bigint primary key,
    username text,
    name text,
    age text,
    phone text,
    email text,
    found_us text,
    goal text,
    motivation text,
    category text,
    source text,
    plan text,
    student_no text unique,
    status text default 'registered',
    paid_amount integer default 0,
    registered_at timestamptz,
    second_due timestamptz,
    last_reminded timestamptz,
    completed_at timestamptz,
    referred_by text,
    bonus_sent boolean default false,
    rules_accepted_at timestamptz,
    rules_version text,
    registration_pack_sent_at timestamptz,
    certificate_eligible boolean default false,
    certificate_issued_at timestamptz,
    certificate_number text unique
);

create table if not exists payments (
    id bigint generated by default as identity primary key,
    user_id bigint references students(user_id) on delete cascade,
    amount integer not null,
    proof_file_id text,
    status text default 'pending',
    created_at timestamptz default now()
);

create table if not exists assignment_submissions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references students(user_id) on delete cascade,
    assignment_key text not null,
    file_id text,
    text text,
    submitted_at timestamptz default now(),
    review_status text default 'pending',
    reviewed_by bigint,
    reviewed_at timestamptz,
    review_note text,
    unique(user_id, assignment_key)
);

create table if not exists support_tickets (
    id bigint generated by default as identity primary key,
    user_id bigint references students(user_id) on delete cascade,
    message text not null,
    status text default 'open',
    created_at timestamptz default now(),
    handled_by bigint
);

create table if not exists moderation_reports (
    id bigint generated by default as identity primary key,
    chat_id bigint,
    message_id bigint,
    user_id bigint,
    username text,
    display_name text,
    message_text text,
    detected_terms text,
    status text default 'pending',
    created_at timestamptz default now(),
    reviewed_by bigint,
    reviewed_at timestamptz,
    decision text
);

create index if not exists idx_students_referred_by on students(referred_by);
create index if not exists idx_students_status on students(status);
create index if not exists idx_payments_status on payments(status);
create index if not exists idx_assignments_user on assignment_submissions(user_id);
create index if not exists idx_assignments_review_status on assignment_submissions(review_status);
create index if not exists idx_support_status on support_tickets(status);

-- The bot server should use a server-side Supabase service role or direct Postgres connection.
-- Do NOT expose that credential in client-side code or Telegram messages.
